### ISSUE TITLE
Update for HAProxy 1.5 release?

### ISSUE THREAD

**Issue by ThrawnCA** [observing/balancerbattle#9]
HAProxy 1.5 is now stable; it may be worth trying it out. And it means that Stud can vanish, so Nginx's operational advantage is gone.

**Comment by 3rd-Eden** [comment]
Going to digg through the code and update where possible and see I can do another round of testing next week.

**Comment by marcellodesales** [comment]
@3rd-Eden Great... it would be great!

**Comment by ThrawnCA** [comment]
And HAProxy 1.6.0 is now out.

**Comment by futurechan** [comment]
and http-proxy 1.13.1
